
DROP TABLE IF EXISTS `oc_storehouse_sales_order`;
CREATE TABLE `oc_storehouse_sales_order` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `sales_order_id` varchar(11) DEFAULT '' COMMENT '订单编号',
  `sales_order_remark` varchar(50) DEFAULT '' COMMENT '摘要',
  `sales_order_give_date` date DEFAULT '0000-00-00' COMMENT '交付日期',
  `sales_order_is_audited` int(2) DEFAULT '0' COMMENT '是否审核',
  `sales_order_date` date DEFAULT '0000-00-00' COMMENT '单据发生日期',
  `customer_id` varchar(50) DEFAULT '' COMMENT '客户/供应商/部门 编号',
  `customer_name` varchar(50) DEFAULT '' COMMENT '客户/供应商/部门 名称',
  `username` varchar(50) DEFAULT '' COMMENT '操作人（英文）',
  `nickname` varchar(50) DEFAULT '' COMMENT '操作人（中文）',
  `clerk_name` varchar(50) DEFAULT '' COMMENT '业务员',
  `goods_id` varchar(11) DEFAULT '' COMMENT '商品编码',
  `goods_name` varchar(50) DEFAULT '' COMMENT '商品名称',
  `goods_spec` varchar(50) DEFAULT '' COMMENT '商品规格',
  `goods_min_unit` varchar(10) DEFAULT '' COMMENT '商品最小单位',
  `goods_rates` varchar(100) DEFAULT '' COMMENT '换算率集合',
  `goods_actual_unit` varchar(10) DEFAULT '' COMMENT '商品实际单位',
  `goods_weight` decimal(10,2) DEFAULT '0.00' COMMENT '商品重量',
  `goods_stock_balance` decimal(10,2) DEFAULT '0.00' COMMENT '商品帐存量',
  `goods_actual_stock_balance` decimal(10,2) DEFAULT '0.00' COMMENT '商品实际数量',
  `goods_cost_price` decimal(10,2) DEFAULT '0.00' COMMENT '商品单价',
  `goods_order_quantity` decimal(10,2) DEFAULT '0.00' COMMENT '商品订购数量',
  `goods_is_free` int(2) DEFAULT '0' COMMENT '商品是否为赠品 0-否 1-是',
  `goods_sales_unit_price` decimal(10,2) DEFAULT '0.00' COMMENT '商品调出单价',
  `goods_sales_total_quantity` decimal(10,2) DEFAULT '0.00' COMMENT '商品调出数量',
  `goods_sales_total_price` decimal(10,2) DEFAULT '0.00' COMMENT '商品调出金额',
  `goods_return_unit_price` decimal(10,2) DEFAULT '0.00' COMMENT '商品退货单价',
  `goods_return_total_quantity` decimal(10,2) DEFAULT '0.00' COMMENT '商品退货数量',
  `goods_return_total_price` decimal(10,2) DEFAULT '0.00' COMMENT '商品退货金额',
  `goods_remark` varchar(20) DEFAULT '' COMMENT '商品备注',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '单据生成时间',
  `update_time` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `status` tinyint(3) DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

INSERT INTO `oc_storehouse_sales_order` VALUES ('3', 'XSDD0000001', 'dfgsfsdf', '2017-10-01', '1', '2017-09-30', 'KH0001', 'XXX市政局', 'admin', '超级管理员', '', 'CP0001', '井盖', 'JQ-300*300', 'kg', '500/箱,1000/吨', '箱', '2000.00', '0.00', '0.00', '0.00', '0.00', '0', '5.50', '4.00', '22.00', '0.00', '0.00', '0.00', 'sdfsfdsdf', '2017-09-18 00:57:01', '0000-00-00 00:00:00', '1');
