
DROP TABLE IF EXISTS `oc_storehouse_gathering_order`;
CREATE TABLE `oc_storehouse_gathering_order` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `gathering_order_type_name` varchar(50) DEFAULT '' COMMENT '收款单类型',
  `gathering_order_id` varchar(11) DEFAULT '' COMMENT '收款单编号',
  `gathering_order_invoice_number` varchar(50) DEFAULT '' COMMENT '发票号码',
  `gathering_order_payment_way` varchar(10) DEFAULT '' COMMENT '支付方式',
  `gathering_order_remark` varchar(50) DEFAULT '' COMMENT '摘要',
  `gathering_order_payment_account` varchar(20) DEFAULT '' COMMENT '支付账户',
  `gathering_order_price` decimal(10,2) DEFAULT '0.00' COMMENT '单据金额',
  `gathering_order_deposit_rate` decimal(4,2) DEFAULT '0.00' COMMENT '折扣率',
  `gathering_order_deposit_after_price` decimal(10,2) DEFAULT '0.00' COMMENT '折后金额',
  `gathering_order_tax_rate` decimal(4,2) DEFAULT '0.00' COMMENT '税率',
  `gathering_order_including_tax_price` decimal(10,2) DEFAULT '0.00' COMMENT '含税金额',
  `gathering_order_receivable_price` decimal(10,2) DEFAULT '0.00' COMMENT '应收金额',
  `gathering_order_actual_payment` decimal(10,2) DEFAULT '0.00' COMMENT '实际支付',
  `gathering_order_payment_date` date DEFAULT '0000-00-00' COMMENT '支付日期',
  `gathering_order_is_audited` int(2) DEFAULT '0' COMMENT '是否审核',
  `audited_date` date DEFAULT NULL COMMENT '审核日期',
  `gathering_order_date` date DEFAULT '0000-00-00' COMMENT '单据发生日期',
  `customer_id` varchar(50) DEFAULT '' COMMENT '客户/供应商/部门 编号',
  `customer_name` varchar(50) DEFAULT '' COMMENT '客户/供应商/部门 名称',
  `clerk_id` varchar(50) DEFAULT '',
  `clerk_name` varchar(50) DEFAULT '' COMMENT '业务员',
  `department` varchar(50) DEFAULT '' COMMENT '部门',
  `storehouse_name` varchar(50) DEFAULT '' COMMENT '所属仓库',
  `invoice_type` varchar(50) DEFAULT '' COMMENT '发票类型',
  `username` varchar(50) DEFAULT '' COMMENT '操作人（英文）',
  `nickname` varchar(50) DEFAULT '' COMMENT '操作人（中文）',
  `out_order_date` date DEFAULT '0000-00-00' COMMENT '单据发生日期',
  `out_order_id` varchar(50) DEFAULT '' COMMENT '单据编号',
  `out_order_price` decimal(10,2) DEFAULT '0.00' COMMENT '单据金额',
  `out_order_account_receivable` decimal(10,2) DEFAULT '0.00' COMMENT '应收金额',
  `already_clear_price` decimal(10,2) DEFAULT '0.00' COMMENT '已核销',
  `no_clear_price` decimal(10,2) DEFAULT '0.00' COMMENT '未核销',
  `now_clear_price` decimal(10,2) DEFAULT '0.00' COMMENT '本次核销',
  `order_remark` varchar(20) DEFAULT '' COMMENT '商品备注',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '单据生成时间',
  `update_time` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `status` tinyint(3) DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO `oc_storehouse_gathering_order` VALUES ('1', '采购收款', 'SKD000001', '', '', '', '', '3.50', '0.00', '0.00', '0.00', '0.00', '3.50', '3.50', '2017-09-15', '1', '', '0000-00-00', 'KH0002', '郑州市市政管理中心', '', '', '', '', '', 'admin', '超级管理员', '2017-09-13', 'XS000001', '15.00', '13.50', '10.00', '3.50', '3.50', 'sdfsdfsd', '2017-09-17 13:48:38', '0000-00-00 00:00:00', '1');
